openapi: 3.0.0
info:
  title: API de Gerenciamento de Tarefas
  description: Documentação da API para o gerenciamento de tarefas (To-Do List)
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
    description: Servidor de Desenvolvimento

paths:
  /tasks:
    get:
      summary: Obter todas as tarefas
      responses:
        '200':
          description: Lista de tarefas obtida com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        description:
                          type: string
                        completed:
                          type: boolean
                  total_tasks:
                    type: integer

    post:
      summary: Criar nova tarefa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
              required:
                - title
      responses:
        '201':
          description: Nova tarefa criada com sucesso

  /tasks/{taskId}:
    get:
      summary: Obter uma tarefa pelo ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID da tarefa a ser buscada
          schema:
            type: integer
      responses:
        '200':
          description: Tarefa obtida com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  completed:
                    type: boolean
        '404':
          description: Tarefa não encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /tasks/{taskId}:
    put:
      summary: Atualizar tarefa existente
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID da tarefa a ser atualizada
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Dados da tarefa a serem atualizados
              properties:
                title:
                  type: string
                description:
                  type: string
                completed:
                  type: boolean
              required:
                - title
      responses:
        '200':
          description: Tarefa atualizada com sucesso

    delete:
      summary: Deletar tarefa existente
      parameters:
        - name: taskId
          in: path
          required: true
          description: ID da tarefa a ser deletada
          schema:
            type: integer
      responses:
        '200':
          description: Tarefa deletada com sucesso
